### ISSUE TITLE
Feature Request: Helper for sending warnings and errors based on the location of a node

### ISSUE THREAD

**Issue by 4th-dimention** [ryanfleury/data_desk#11]
As we already discussed, something like `DataDeskWarning(node, "My message %d", x);` or whatever other features you'd put into it.

**Comment by ryanfleury** [comment]
Implemented this in most recent commits, check out `DataDeskError` and `DataDeskWarning`. Basically the exact API you suggested. Let me know if you think of further extensions to it that would be useful.
