### ISSUE TITLE
Feature Request: Upgrade for the alternate names

### ISSUE THREAD

**Issue by 4th-dimention** [ryanfleury/data_desk#8]
Right now the alternate names are:
```C
    char *name_lowercase_with_underscores;
    char *name_uppercase_with_underscores;
    char *name_upper_camel_case;
    char *name_lower_camel_case;
```

I think this could be expanded out to cover basically every common case (besides InTeRnEt SaRcAsM case perhaps)

There are basically three ways to print each word in an identifier: `word` `Word` `WORD`
The first word may want a special rule of it's own: `first` `First` `FIRST`
Then there are two ways to space things out: `_` or nothing

That gives 18 alternates. So what I'm proposing is something like:

```
   // Alternate name flags
   NameAlternate_firstword,
   NameAlternate_firstWord,
   NameAlternate_firstWORD,
   NameAlternate_Firstword,
   NameAlternate_FirstWord,
   NameAlternate_FirstWORD,
   NameAlternate_FIRSTword,
   NameAlternate_FIRSTWord,
   NameAlternate_FIRSTWORD,
   ... etc for Underscore versions

    // In the struct
    char *name_alternate[18];
```

And then maybe build these on demand when they are requested? With something like:
`DataDeskAlternateName(node, NameAlternate_firstWord);`

**Comment by ryanfleury** [comment]
Implemented these in e1a01eeccfba1fc9d386c7f1376a22362a238751; you can now call `DataDeskGetTransformedString` or `DataDeskGetTransformedStringDifferentFirstWord` on a `DataDeskNode` to get a transformed string of a particular style. These are just always computed right now, but let me know if you run into performance issues and I can start lazily-evaluating them.
